### ISSUE TITLE
Unclear if NPM or file cannot be found: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by votecoffee** [inveniosoftware/pynpm#12]
Package version (if known): 0.1.2

## Describe the bug
When I try to run pkg.install(), I get the error "[WinError 2] The system cannot find the file specified"

I suspect it can't find npm vs not being able to find the file.  I'd expect it to tell me it can't find npm to make it clear.

But NPM is findable in my path.  I even tried manually appending the NPM bin folder to the path without success.  And I can run NPM from the command line.  So I'm at a loss as to what the issue is.

## Steps to Reproduce

# install npm and add to path
pip install pynpm

```
import os
import sys
from pynpm import NPMPackage

def install_dependecies():
    npm_path = r'C:\Program Files\nodejs\node_modules\npm\bin'
    sys.path.append(npm_path)
    executable = 'npm.cmd'
    for p in os.environ["PATH"].split(os.pathsep):
        if os.path.exists(os.path.join(p, executable)):
            print('Found NPM')

    #jquery_pkg_path = os.getcwd() + r'\3rdparty\jquery-ui-1.12.1.custom\package.json'
    #jquery_pkg_path = os.getcwd() + '/3rdparty/jquery-ui-1.12.1.custom/package.json'
    #jquery_pkg_path = './3rdparty/jquery-ui-1.12.1.custom/package.json'
    #jquery_pkg_path = r'C:\Users\user\source\repos\myproject\3rdparty\jquery-ui-1.12.1.custom\package.json'
    jquery_pkg_path = 'C:/Users/user/source/repos/myproject/3rdparty/jquery-ui-1.12.1.custom/package.json'
    if os.path.exists(jquery_pkg_path) == True:
        print('File exists: ' + jquery_pkg_path)
    else:
        print('File does not exist: ' + jquery_pkg_path)
    jquery_pkg = NPMPackage(jquery_pkg_path)
    jquery_pkg.install()
```

## Expected behavior
I expect it to tell me whether it's failing to find NPM or my file.  I suspect it is failing to find NPM.

## Screenshots (if applicable)
I get the following output:
> Found NPM
> File exists: C:/Users/user/source/repos/myproject/3rdparty/jquery-ui-1.12.1.custom/package.json
> C:/Users/user/source/repos/myproject/3rdparty/jquery-ui-1.12.1.custom/package.json
> 2021-02-22 09:34:49,469 ERROR    [Main.py:59 main] [WinError 2] The system cannot find the file specified
> Traceback (most recent call last):
>   File "C:\Users\user\source\repos\myproject\Main.py", line 57, in main
>     api.treeview_dictionary_editable.install_dependecies()
>   File "C:\Users\user\source\repos\myproject\api\treeview_dictionary_editable.py", line 17, in install_dependecies
>     jquery_pkg.install()
>   File "C:\Users\user\source\repos\myproject\env\lib\site-packages\pynpm\package.py", line 76, in _run_npm
>     **kwargs
>   File "C:\Users\user\source\repos\myproject\env\lib\site-packages\pynpm\utils.py", line 25, in run_npm
>     cwd=pkgdir,
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\subprocess.py", line 339, in call
>     with Popen(*popenargs, **kwargs) as p:
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\subprocess.py", line 800, in __init__
>     restore_signals, start_new_session)
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\subprocess.py", line 1207, in _execute_child
>     startupinfo)
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> [WinError 2] The system cannot find the file specified
> Stack trace:
>  >  File "C:\Users\user\source\repos\myproject\Main.py", line 77, in <module>
>  >    main()

**Comment by votecoffee** [comment]
I dug a little further and it couldn't find NPM.  If I run subprocess with the shell=True flag, it can find NPM.  I'm not sure how to propagate this through the pynpm utility though.
```
    npm_bin='npm'
    cmd = '-h'
    command = [npm_bin, cmd]
    print(subprocess.run(command)) # Fails!!!
    print(subprocess.run(command, shell=True)) # Works!!!
```

**Comment by votecoffee** [comment]
It looks like subprocess returns this error instead if the package name is invalid: [WinError 267] The directory name is invalid
This error indicates the npm command is invalid: [WinError 2] The system cannot find the file specified

**Comment by travisjwalter** [comment]
@votecoffee I am not sure if you found a workaround for this but for anyone that has a similar issue and looks here, the workaround I wrote executed the npm commands as requested with some edits to the package code. 

**_PLEASE NOTE, THIS WORKAROUND CAN INTRODUCE SOME SECURITY ISSUES SO DO NOT USE ON ANY PRODUCTION SYSTEM_**

To work around the bug, I went into the `Lib\site-packages\pynpm` of my virtual environment and edited the `utils.py` script. From my research, the [WinError 2] comes from not being able to run the specific command passed to the subprocess call. By adding `shell=True` to the `subprocess.call()` and `subprocess.Popen()` returns, the subprocess call should be able to run the commands, thus solving the issue.

 _Adding `shell=True` can introduce some security issues as it could allow a client to run arbitrary commands on the shell of your machine. Please do not use this workaround on any production system._ If anyone has a solution to this security issue, please comment ;D

For reference, here is my edited util.py:
```
from __future__ import absolute_import, print_function

import os
import subprocess
import sys


def run_npm(pkgdir, cmd, args=None, npm_bin='npm', wait=True):
    """Run NPM."""
    command = [npm_bin, cmd] + list(args)

    if wait:
        return subprocess.call(
            command,
            cwd=pkgdir,
            shell=True
        )
    else:
        return subprocess.Popen(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            cwd=pkgdir,
            shell=True
        )
```

Hope this helps!
